/// <reference types="node" />
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // db push / migrate uses the DIRECT connection (bypasses PgBouncer)
    // so it can run DDL statements (CREATE TABLE, ALTER TABLE, etc.)
    url: process.env["DIRECT_URL"],
  },
});

